### ISSUE TITLE
Repositories information display on EFES

### ISSUE THREAD

**Issue by mparani70** [MedCyprus/MedCyprusEFES#24]
@gabrielbodard @emylonas 

The information on Repositories that appears on EFES needs to reflect the information in locations.xml. Currently, entries on Repositories include the same fields as Monuments.

**Comment by emylonas** [comment]
Repositories have 
* Greek and English `<placeName>` (same as monuments)
* `<location><geo>` (same as monuments)
* A WikiData idno (only one museum) (same as monuments)
* `<bibl>` which refers to their website - Is this the correct element?  (monuments also have bibl, but it's handled differently) This looks more like an external link or perhaps some other name like "Repository Website". 

The only different element is `<location><placeName>` - is this different because in order to avoid indexing repositories by district and diocese as we do with the monuments? 
As we will be breaking out processing for repositories into its own set of templates, and will have to create new indexing fields, it doesn't matter if this is called `<placeName>` or `<location><placeName>`.

**Comment by mparani70** [comment]
I agree that Repository Website is more appropriate than bibl, since we are not going to include any bibliographic references here.

**Comment by emylonas** [comment]
Add "n/a" for External Resources and close

**Comment by emylonas** [comment]
Behaves as described above. 
closing with commit f16f408f
