### ISSUE TITLE
Locations - Monument 33

### ISSUE THREAD

**Issue by mparani70** [MedCyprus/MedCyprusEFES#29]
Monument 33 (xml:id="KoutsoventisTrinity") appears out of sequence on EFES and needs to be returned to its proper order.

**Comment by emylonas** [comment]
I'm fairly sure that the indices are output alphabetically using the value of the `xml:id`, which is the text string identifying the monument. This isn't noticeable, because the monuments are already listed alphabetically in locations.xml and are numbered in that order. However, the three entries for "Koutsoventis, Monastery of Saint John Chrysostom" are not in alphabetical order.

- 33 KoutsoventisTrinity
- 34 KoutsoventisPanagia
- 35 KoutsoventisSaviour

KoutsoventisTrinity is alphabetically last, but it has the number 33.

I think the simplest thing to do might be to change the numbering of the files, so that they sort properly in the display. As far as I can tell, any linking to the inscription xml is done using the `@xml:id`, and not the entry number, which is used only as part of the locations index display. I tried it and it works. 

The alternative might be to change KoutsoventisTrinity to KoutsoventisHolyTrinity in the @xml:id in locations.xml as well as in the `origPlace` element in each of the 4 inscriptions for this monument. That would make it sort first, alphabetically.

**Comment by emylonas** [comment]
I was partially correct - the locations are being displayed in alphabetical order. But it's based not on the `@xml:id`, but on the first `<placeName>`. In this case, the monuments were listed as:

- Koutsoventis, Monastery of St John Chrysostom, Holy Trinity chapel
- Koutsoventis, Monastery of Saint John Chrysostom, Panagia Aphendrika
- Koutsoventis, Monastery of Saint John Chrysostom, Saviour

_St_ alphabetizes after _Saint_... I changed it to read  _Koutsoventis, Monastery of St John Chrysostom, Holy Trinity chapel_ and everything seems to display as expected. closing with commit 855fee17

**Comment by mparani70** [comment]
[like]  Maria Parani reacted to your message:
________________________________
